### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by mliq** [kcyarn/markdown-document#4] opened 2016-06-16 21:48 UTC
[Enter steps to reproduce below:]
1. Open outline with keyboard shortcut
2. Click a heading in outline

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.1.1
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:685:20)
    at Cursor.module.exports.Cursor.autoscroll (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:690:51)
    at Cursor.module.exports.Cursor.changePosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:675:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at /Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1527:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1780:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Users/mliquori/Dropbox/config/Backup/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1526:19)
    at HTMLAnchorElement.MarkdownDocumentView.handleClick (/Users/mliquori/Dropbox/config/atom/packages/markdown-document/lib/markdown-document-view.coffee:145:14)
```
### Commands

```
     -0:18 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:18 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:18 editor:newline (atom-text-editor.editor.is-focused)
     -0:17 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:16.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:15.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -0:14.6.0 editor:move-to-next-word-boundary (atom-text-editor.editor.is-focused)
  2x -0:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:05.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.5.0 link:open (atom-text-editor.editor.is-focused)
     -0:03.2.0 markdown-document:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "path-hyperclick",
      "file-hyperclick",
      "navigation-history",
      "split-diff",
      "tree-view-autoresize",
      "symbol-gen",
      "semanticolor",
      "fonts",
      "pigments",
      "rnn-writer",
      "language-javascript-semantic",
      "language-javascript-jsx",
      "git-diff-details",
      "language-javascript-better",
      "webbox-color",
      "atom-beautify",
      "tree-view-git-branch",
      "tree-view-git-status",
      "save-session",
      "js-refactor",
      "refactor",
      "git-history",
      "unsaved-changes",
      "Tern",
      "language-markdown",
      "markdown-preview",
      "autocomplete-ctags",
      "atom-ctags",
      "ctags-status",
      "change-case",
      "markdown-assistant"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view-filter",
      "bookmarks",
      "merge-conflicts",
      "pinned-tabs",
      "markdown-pdf",
      "copy-filename",
      "git-diff-popup",
      "live-archive"
    ],
    "projectHome": "/Users/mliquori/Dropbox/tech/projects",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-syntax, v0.4.6
atom-ternjs, v0.14.2
autoclose-html, v0.23.0
autocomplete-modules, v1.5.1
block-travel, v1.0.4
color-picker, v2.1.1
copy-filename, v1.0.1
docblockr, v0.7.3
editorconfig, v1.4.1
file-icons, v1.7.15
goto-last-edit, v0.3.2
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-markdown, v0.1.3
indent-guide-improved, v1.4.9
js-hyperclick, v1.4.2
jumpy, v3.0.3
language-babel, v2.28.0
language-diff, v0.4.0
last-cursor-position, v0.9.0
line-diff-details, v1.3.5
linter, v1.11.10
linter-eslint, v7.2.2
local-history, v3.3.0
markdown-document, v0.1.1
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.4.0
markdown-writer, v2.3.4
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-cursorline, v0.2.0
pinned-tabs, v0.2.5
project-manager, v2.9.7
recent-files-fuzzy-finder, v0.2.4
remember-file-positions, v0.2.2
tree-view-filter, v0.4.1

# Dev
No dev packages
```

**Comment by kcyarn** [comment] 2016-06-17 11:19
Did you run any other commands before this occurred or does it always happen? The error occurs because the text editor was destroyed and on click can't find the text editor's buffer because it doesn't exist. There isn't anything in this package that actually destroys the texteditor buffer. All it does is find it, get the filename, go to the line, and save it.

I uninstalled the dev, installed a clean copy using apm, and can't reproduce the problem. Were there any other panes open or a file closed or something?

**Comment by kcyarn** [comment] 2016-06-17 16:39
Just a thought...there were a few issues with opening the same file in multiple panes. I believe those are resolved in the dev branch. There were changes made to the click event, which may resolve this issue.

Commit d140140f7665cb4eefd56c3ea2800cbda957ee9d

**Closed as completed** 2016-07-03 18:23 UTC
Labels: bug
