### ISSUE TITLE
Does not toggle anything when clicking toggle

### ISSUE THREAD

**Issue by philwinder** [kcyarn/markdown-document#16] opened 2017-01-22 10:18 UTC
Atom 1.13.0 on OSX.

When pressing toggle, nothing happens. When pressing refresh, I see the same as #15.

Couldn't find any obvious error logs to show what was (not) happening.

Nice idea though. Looking forward to seeing it working.

**Comment by kcyarn** [comment] 2017-01-22 17:39
Duplicate of #15. If this package is currently essential to your workflow, please downgrade to atom to 1.12.*

**Closed as completed by kcyarn** 2017-01-22 17:39 UTC
